# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
DEFAULT_USERNAME='alexander'
CMD_MAX_EXEC_TIME=5

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mad"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"


# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=()

source $ZSH/oh-my-zsh.sh


# Customize to your needs...
export PATH="/bin:${PATH}"

export PATH="/sbin:${PATH}"

export PATH="/usr/bin:${PATH}"
export PATH="/usr/sbin:${PATH}"

export PATH="/usr/local/bin:${PATH}"
export PATH="/usr/local/sbin:${PATH}"
export PATH="/usr/local/Cellar:${PATH}"
export PATH="/usr/local/php5/bin:$PATH"
export PATH="/usr/local/mysql/bin:${PATH}"
export PATH="/usr/local/pgsql/bin:${PATH}"

export PATH="/opt/X11/bin:${PATH}"
export PATH="/opt/local/bin:${PATH}"
export PATH="/opt/local/sbin:${PATH}"

export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"


export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacad
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
[ $USER != $DEFAULT_USERNAME ] && local username='%n@%m '


HISTSIZE=10000
SAVEHIST=10000
DISABLE_CORRECTION="true"


unsetopt correct_all
setopt INC_APPEND_HISTORY
setopt NO_SHARE_HISTORY


export ANSIBLE_NOCOWS=1


zstyle ':completion:*:(all-|)files' ignored-patterns "(*.pyc|*~)"
export FZF_DEFAULT_COMMAND='ag -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi


# go things
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin


# external source of files
source ~/.bash_alias
