---
- hosts: localhost
  roles:
    - { role: homebrew }
    - { role: cask }
    - { role: pip }
    - { role: dotfiles }
    - { role: git }
    - { role: zsh, become: yes, become_method: sudo }
    - { role: vim }
