---

- name: copy .zshrc
  copy: src=zshrc dest=~/.zshrc force=yes

- name: copy mad.zsh-theme
  copy: src=mad.zsh-theme dest=~/.oh-my-zsh/themes force=yes

- name: set zsh as default shell
  become: yes
  become_method: sudo
  shell: chsh -s "$(command -v zsh)" "${USER}"
