---

- name: copy .gitconfig in to user
  copy: src=gitconfig dest=~/.gitconfig force=yes

- name: copy .gitignore in to user
  copy: src=gitignore dest=~/.gitignore force=yes

- name: copy  .git-prompt.sh in to user
  copy: src=git-prompt.sh dest=~/.git-prompt.sh force=yes

- name: set .gitignore
  shell: git config --global core.excludesfile ~/.gitignore
